export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESSFUL = 'USER_SIGNUP_SUCCESSFUL';
export const USER_SIGNUP_FAILED = 'USER_SIGNUP_FAILED';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESSFUL = 'USER_LOGIN_SUCCESSFUL';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const SIGNOUT = 'SIGNOUT';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const GET_LISTINGS_REQUEST = 'GET_LISTINGS_REQUEST';
export const GET_LISTINGS_SUCCESSFUL = 'GET_LISTINGS_SUCCESSFUL';
export const GET_LISTINGS_FAILED = 'GET_LISTINGS_FAILED';

export const GET_LISTING_DETAILS_REQUEST = 'GET_LISTING_DETAILS_REQUEST';
export const GET_LISTING_DETAILS_SUCCESSFUL = 'GET_LISTINGS_DETAIL_SUCCESSFUL';
export const GET_LISTING_DETAILS_FAILED = 'GET_LISTING_DETAILS_FAILED';

export const POST_LISTINGS_REQUEST = 'POST_LISTINGS_REQUEST';
export const POST_LISTINGS_SUCCESSFUL = 'POST_LISTINGS_SUCCESSFUL';
export const POST_LISTINGS_FAILED = 'POST_LISTINGS_FAILED';

export const GOOGLE_AUTH_SUCCESS = 'GOOGLE_AUTH_SUCCESS';
export const GOOGLE_AUTH_FAIL = 'GOOGLE_AUTH_FAIL';
